/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.artepublicidaded;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Genes
 */
public class RegistroForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroForm.class.getName());

    /**
     * Creates new form RegistroForm
     */
    public RegistroForm() {
        initComponents();
        configurarPlaceholderUsuario();
        configurarPlaceholdersClaves();
        this.setLocationRelativeTo(null);

    }
    
    private void configurarPlaceholderUsuario() {
        txtNuevoUsuario.setForeground(Color.GRAY);
        txtNuevoUsuario.setText("Usuario");
        
        txtNuevoUsuario.addFocusListener(new java.awt.event.FocusAdapter(){
           public void focusGainer(java.awt.event.FocusEvent evt){
               if (txtNuevoUsuario.getText().equals("Usuario")){
                   txtNuevoUsuario.setText("");
                   txtNuevoUsuario.setForeground(Color.BLACK);
               }
           } 
           public void focusLost(java.awt.event.FocusEvent evt){
               if (txtNuevoUsuario.getText().isEmpty()){
                   txtNuevoUsuario.setForeground(Color.GRAY);
                   txtNuevoUsuario.setText("Usuario");
               }
           }
        });
    }
    
    private void configurarPlaceholdersClaves(){
         lblPlaceholderClave.setVisible(true);
    txtNuevaClave.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            lblPlaceholderClave.setVisible(false);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtNuevaClave.getPassword().length == 0) {
                lblPlaceholderClave.setVisible(true);
            }
        }
    });

    lblPlaceholderConfirmar.setVisible(true);
    txtConfirmarClave.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            lblPlaceholderConfirmar.setVisible(false);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtConfirmarClave.getPassword().length == 0) {
                lblPlaceholderConfirmar.setVisible(true);
            }
        }
    });
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPlaceholderClave = new javax.swing.JLabel();
        txtNuevoUsuario = new javax.swing.JTextField();
        lblPlaceholderClave1 = new javax.swing.JLabel();
        lblPlaceholderClave2 = new javax.swing.JLabel();
        lblPlaceholderClave3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblPlaceholderConfirmar = new javax.swing.JLabel();
        txtConfirmarClave = new javax.swing.JPasswordField();
        txtNuevaClave = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(380, 300));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPlaceholderClave.setForeground(new java.awt.Color(150, 150, 150));
        lblPlaceholderClave.setText("Contraseña");
        getContentPane().add(lblPlaceholderClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 70, 30));
        getContentPane().add(txtNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 150, 30));

        lblPlaceholderClave1.setForeground(new java.awt.Color(150, 150, 150));
        lblPlaceholderClave1.setText("Contraseña");
        getContentPane().add(lblPlaceholderClave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 70, 30));

        lblPlaceholderClave2.setForeground(new java.awt.Color(150, 150, 150));
        lblPlaceholderClave2.setText("Contraseña");
        getContentPane().add(lblPlaceholderClave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 70, 30));

        lblPlaceholderClave3.setForeground(new java.awt.Color(150, 150, 150));
        lblPlaceholderClave3.setText("Contraseña");
        getContentPane().add(lblPlaceholderClave3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 70, 30));

        jPanel2.setPreferredSize(new java.awt.Dimension(380, 300));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setText("Register");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);
        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        lblPlaceholderConfirmar.setForeground(new java.awt.Color(150, 150, 150));
        lblPlaceholderConfirmar.setText("Confirmar contraseña");
        jPanel2.add(lblPlaceholderConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 130, 30));
        jPanel2.add(txtConfirmarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 150, 30));
        jPanel2.add(txtNuevaClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 150, 30));

        jLabel1.setText("Registrar Nuevo Usuario");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   //Generamos la carpeta donde guardaremos los usuarios por el momento (luego nos enseñaran a usar SQL)
    private void guardarUsuario(String usuario, String clave){
        try (java.io.FileWriter fw = new java.io.FileWriter("usuarios.txt", true);
         java.io.PrintWriter pw = new java.io.PrintWriter(fw)) {
        pw.println(usuario + "," + clave);
    } catch (java.io.IOException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
    }
}
    private boolean usuarioExiste(String usuario){
        java.io.File archivo = new java.io.File("usuarios.txt");
        if (!archivo.exists()){
            return false;
        }
        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
        String linea;
        while ((linea = br.readLine()) != null) {
            String[] partes = linea.split(",");
            if (partes.length > 0 && partes[0].equals(usuario)) {
                return true;
            }
        }
    } catch (java.io.IOException e) {
        JOptionPane.showMessageDialog(this, "Error al leer: " + e.getMessage());
    }
    return false;
}
        
        
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String nuevoUsuario = txtNuevoUsuario.getText().trim();
        String nuevaClave = new String(txtNuevaClave.getPassword());
        String confirmarClave = new String(txtConfirmarClave.getPassword());
        
        //Ingresamos las validaciones
        if (nuevoUsuario.isEmpty() || nuevaClave.isEmpty()){
            JOptionPane.showMessageDialog(this, "Completa todos los campos", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!nuevaClave.equals(confirmarClave)){
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (usuarioExiste(nuevoUsuario)){
            JOptionPane.showMessageDialog(this, "Ese usuario ya existe", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        guardarUsuario(nuevoUsuario, nuevaClave);
        JOptionPane.showMessageDialog(this, "usuario registrado con exito");
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPlaceholderClave;
    private javax.swing.JLabel lblPlaceholderClave1;
    private javax.swing.JLabel lblPlaceholderClave2;
    private javax.swing.JLabel lblPlaceholderClave3;
    private javax.swing.JLabel lblPlaceholderConfirmar;
    private javax.swing.JPasswordField txtConfirmarClave;
    private javax.swing.JPasswordField txtNuevaClave;
    private javax.swing.JTextField txtNuevoUsuario;
    // End of variables declaration//GEN-END:variables
}
